/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.work.on.kafka.order.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2258082800028113348L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerAvroModel\",\"namespace\":\"com.work.on.kafka.order.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"colors\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Color\",\"fields\":[{\"name\":\"hex\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}},{\"name\":\"subscriptionType\",\"type\":{\"type\":\"enum\",\"name\":\"SubscriptionType\",\"symbols\":[\"BASIC\",\"STANDARD\",\"PREMIUM\"]}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"subscriptionFinishAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"active\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<CustomerAvroModel> ENCODER =
      new BinaryMessageEncoder<CustomerAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerAvroModel> DECODER =
      new BinaryMessageDecoder<CustomerAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String name;
  private java.util.List<com.work.on.kafka.order.avro.model.Color> colors;
  private com.work.on.kafka.order.avro.model.SubscriptionType subscriptionType;
  private java.time.Instant createdAt;
  private java.time.Instant subscriptionFinishAt;
  private boolean active;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param colors The new value for colors
   * @param subscriptionType The new value for subscriptionType
   * @param createdAt The new value for createdAt
   * @param subscriptionFinishAt The new value for subscriptionFinishAt
   * @param active The new value for active
   */
  public CustomerAvroModel(java.lang.String id, java.lang.String name, java.util.List<com.work.on.kafka.order.avro.model.Color> colors, com.work.on.kafka.order.avro.model.SubscriptionType subscriptionType, java.time.Instant createdAt, java.time.Instant subscriptionFinishAt, java.lang.Boolean active) {
    this.id = id;
    this.name = name;
    this.colors = colors;
    this.subscriptionType = subscriptionType;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.subscriptionFinishAt = subscriptionFinishAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.active = active;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return colors;
    case 3: return subscriptionType;
    case 4: return createdAt;
    case 5: return subscriptionFinishAt;
    case 6: return active;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: colors = (java.util.List<com.work.on.kafka.order.avro.model.Color>)value$; break;
    case 3: subscriptionType = (com.work.on.kafka.order.avro.model.SubscriptionType)value$; break;
    case 4: createdAt = (java.time.Instant)value$; break;
    case 5: subscriptionFinishAt = (java.time.Instant)value$; break;
    case 6: active = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'colors' field.
   * @return The value of the 'colors' field.
   */
  public java.util.List<com.work.on.kafka.order.avro.model.Color> getColors() {
    return colors;
  }


  /**
   * Sets the value of the 'colors' field.
   * @param value the value to set.
   */
  public void setColors(java.util.List<com.work.on.kafka.order.avro.model.Color> value) {
    this.colors = value;
  }

  /**
   * Gets the value of the 'subscriptionType' field.
   * @return The value of the 'subscriptionType' field.
   */
  public com.work.on.kafka.order.avro.model.SubscriptionType getSubscriptionType() {
    return subscriptionType;
  }


  /**
   * Sets the value of the 'subscriptionType' field.
   * @param value the value to set.
   */
  public void setSubscriptionType(com.work.on.kafka.order.avro.model.SubscriptionType value) {
    this.subscriptionType = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'subscriptionFinishAt' field.
   * @return The value of the 'subscriptionFinishAt' field.
   */
  public java.time.Instant getSubscriptionFinishAt() {
    return subscriptionFinishAt;
  }


  /**
   * Sets the value of the 'subscriptionFinishAt' field.
   * @param value the value to set.
   */
  public void setSubscriptionFinishAt(java.time.Instant value) {
    this.subscriptionFinishAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(boolean value) {
    this.active = value;
  }

  /**
   * Creates a new CustomerAvroModel RecordBuilder.
   * @return A new CustomerAvroModel RecordBuilder
   */
  public static com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder newBuilder() {
    return new com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder();
  }

  /**
   * Creates a new CustomerAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerAvroModel RecordBuilder
   */
  public static com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder newBuilder(com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder other) {
    if (other == null) {
      return new com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder();
    } else {
      return new com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CustomerAvroModel RecordBuilder by copying an existing CustomerAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CustomerAvroModel RecordBuilder
   */
  public static com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder newBuilder(com.work.on.kafka.order.avro.model.CustomerAvroModel other) {
    if (other == null) {
      return new com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder();
    } else {
      return new com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerAvroModel>
    implements org.apache.avro.data.RecordBuilder<CustomerAvroModel> {

    private java.lang.String id;
    private java.lang.String name;
    private java.util.List<com.work.on.kafka.order.avro.model.Color> colors;
    private com.work.on.kafka.order.avro.model.SubscriptionType subscriptionType;
    private java.time.Instant createdAt;
    private java.time.Instant subscriptionFinishAt;
    private boolean active;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.colors)) {
        this.colors = data().deepCopy(fields()[2].schema(), other.colors);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.subscriptionType)) {
        this.subscriptionType = data().deepCopy(fields()[3].schema(), other.subscriptionType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.subscriptionFinishAt)) {
        this.subscriptionFinishAt = data().deepCopy(fields()[5].schema(), other.subscriptionFinishAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.active)) {
        this.active = data().deepCopy(fields()[6].schema(), other.active);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.work.on.kafka.order.avro.model.CustomerAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.colors)) {
        this.colors = data().deepCopy(fields()[2].schema(), other.colors);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.subscriptionType)) {
        this.subscriptionType = data().deepCopy(fields()[3].schema(), other.subscriptionType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.subscriptionFinishAt)) {
        this.subscriptionFinishAt = data().deepCopy(fields()[5].schema(), other.subscriptionFinishAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.active)) {
        this.active = data().deepCopy(fields()[6].schema(), other.active);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'colors' field.
      * @return The value.
      */
    public java.util.List<com.work.on.kafka.order.avro.model.Color> getColors() {
      return colors;
    }


    /**
      * Sets the value of the 'colors' field.
      * @param value The value of 'colors'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setColors(java.util.List<com.work.on.kafka.order.avro.model.Color> value) {
      validate(fields()[2], value);
      this.colors = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'colors' field has been set.
      * @return True if the 'colors' field has been set, false otherwise.
      */
    public boolean hasColors() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'colors' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearColors() {
      colors = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriptionType' field.
      * @return The value.
      */
    public com.work.on.kafka.order.avro.model.SubscriptionType getSubscriptionType() {
      return subscriptionType;
    }


    /**
      * Sets the value of the 'subscriptionType' field.
      * @param value The value of 'subscriptionType'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setSubscriptionType(com.work.on.kafka.order.avro.model.SubscriptionType value) {
      validate(fields()[3], value);
      this.subscriptionType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriptionType' field has been set.
      * @return True if the 'subscriptionType' field has been set, false otherwise.
      */
    public boolean hasSubscriptionType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'subscriptionType' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearSubscriptionType() {
      subscriptionType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriptionFinishAt' field.
      * @return The value.
      */
    public java.time.Instant getSubscriptionFinishAt() {
      return subscriptionFinishAt;
    }


    /**
      * Sets the value of the 'subscriptionFinishAt' field.
      * @param value The value of 'subscriptionFinishAt'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setSubscriptionFinishAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.subscriptionFinishAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriptionFinishAt' field has been set.
      * @return True if the 'subscriptionFinishAt' field has been set, false otherwise.
      */
    public boolean hasSubscriptionFinishAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'subscriptionFinishAt' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearSubscriptionFinishAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder setActive(boolean value) {
      validate(fields()[6], value);
      this.active = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public com.work.on.kafka.order.avro.model.CustomerAvroModel.Builder clearActive() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerAvroModel build() {
      try {
        CustomerAvroModel record = new CustomerAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.colors = fieldSetFlags()[2] ? this.colors : (java.util.List<com.work.on.kafka.order.avro.model.Color>) defaultValue(fields()[2]);
        record.subscriptionType = fieldSetFlags()[3] ? this.subscriptionType : (com.work.on.kafka.order.avro.model.SubscriptionType) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.time.Instant) defaultValue(fields()[4]);
        record.subscriptionFinishAt = fieldSetFlags()[5] ? this.subscriptionFinishAt : (java.time.Instant) defaultValue(fields()[5]);
        record.active = fieldSetFlags()[6] ? this.active : (java.lang.Boolean) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CustomerAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










