/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.work.on.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum FileType implements org.apache.avro.generic.GenericEnumSymbol<FileType> {
  IMAGE, VIDEO, DOCUMENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FileType\",\"namespace\":\"com.work.on.kafka.order.avro.model\",\"symbols\":[\"IMAGE\",\"VIDEO\",\"DOCUMENT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
