/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.work.on.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum SubscriptionType implements org.apache.avro.generic.GenericEnumSymbol<SubscriptionType> {
  BASIC, STANDARD, PREMIUM  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SubscriptionType\",\"namespace\":\"com.food.ordering.system.kafka.order.avro.model\",\"symbols\":[\"BASIC\",\"STANDARD\",\"PREMIUM\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
